---
title: "My Blog
date: 2018-09-09
author:THe Legend
email:Mnguyasdsf
description: > # this means to ignore newlines until "baseurl:"
Wasssup
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
---
